language: node_js # Для сборки нужен будет NodeJS
node_js:
  stable # Выбираем последню стабильную версию NodeJS
script:
  npm run testlint # Запускаем продакшен-сборку, скрипт из `package.json`
  before_install:
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
deploy:
  provider: pages # Используем возможности GithubPages
  skip_cleanup: true # Не чистим рабочую директорию
  # GITHUB_TOKEN — код, обеспечивающий интеграцию Тревиса и Гитхаба.
  # Нужно сгенерировать тут: https://github.com/settings/tokens и добавить в настройки репозитория в Тревисе
  github_token: $GITHUB_TOKEN

